name: MaSuiteWarps
main: dev.masa.masuitewarps.bukkit.MaSuiteWarps
version: ${project.version}
author: Masagameplay
depends: [ MaSuiteCore ]
softdepend: [ Multiverse, Multiworld ]
loadbefore: [ Essentials ]
api-version: 1.13
commands:
  setwarp:
    permission: masuitewarps.warp.set
  warp:
    permission: masuitewarps.warp